"""initial_schema

Revision ID: 07b6dca5c13d
Revises: 
Create Date: 2026-03-01 13:21:07.266834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b6dca5c13d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersession',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_usersession_session_id'), 'usersession', ['session_id'], unique=False)
    op.create_table('searchhistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_idea', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['usersession.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchhistory_id'), 'searchhistory', ['id'], unique=False)
    op.create_index(op.f('ix_searchhistory_session_id'), 'searchhistory', ['session_id'], unique=False)
    op.drop_table('analysis_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('user_idea', sa.TEXT(), nullable=True),
    sa.Column('result_json', sa.TEXT(), nullable=True),
    sa.Column('risk_level', sa.TEXT(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_searchhistory_session_id'), table_name='searchhistory')
    op.drop_index(op.f('ix_searchhistory_id'), table_name='searchhistory')
    op.drop_table('searchhistory')
    op.drop_index(op.f('ix_usersession_session_id'), table_name='usersession')
    op.drop_table('usersession')
    # ### end Alembic commands ###
